HEAD_DEPTH: "/raw_head_depth"
HAND_DEPTH: "/raw_hand_depth"
HAND_DEPTH_UNSCALED: "/raw_hand_depth_unscaled"
HAND_RGB: "/hand_rgb"

COMPRESSED_IMAGES: "/compressed_images"

FILTERED_HEAD_DEPTH: "/filtered_head_depth"
FILTERED_HAND_DEPTH: "/filtered_hand_depth"

MASK_RCNN_VIZ_TOPIC: "/mask_rcnn_visualizations"
DETECTIONS_TOPIC: "/mask_rcnn_detections"
IMAGE_SCALE: "/image_scale"

ROBOT_STATE: "/robot_state"
TEXT_TO_SPEECH: "/text_to_speech"


# Remote robot topics
ROBOT_CMD_TOPIC: "/remote_robot_cmd"
CMD_ENDED_TOPIC: "/remote_robot_cmd_ended"
INIT_REMOTE_ROBOT: "/init_remote_robot"
KILL_REMOTE_ROBOT: "/kill_remote_robot"
